# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build & Run
        run: |
          npm install -g yarn
          yarn
          yarn build
          yarn start

      - name: Commit files
        run: |
          git config --local user.email "hodade@gmail.com"
          git config --local user.name "hodade bot"
          git status | grep modified && git add src/.json && git commit -v -m "[Bot] GitHub Actions - auto run" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Current Directory Check 
        run: |
          pwd
          cd
          pwd

      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: https://github.com/CodeForAomori/covid19.git
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, defaults to `master`.

      - name: copy news.json
        run: |
          pwd 

      - name: push 
        run: |
          pwd 


